### PR TITLE
Fix conversion for rpy2>3.4.2

### PR DESCRIPTION
**Pull request by scottgigante**
Copying fix from https://github.com/theislab/anndata2ri/issues/63#issuecomment-879677201

Credit to @liuzj039 

cc @flying-sheep

### CODE REVIEW

**Comment by LouisFaure** [comment]
Thanks! It would be great to see this merged! I tend to forget to specify rpy2 version each time in any new environments and always end up with conversion errors!

**Comment by flying-sheep** [comment]
Going to use the original PR: #66

**Comment by scottgigante** [comment]
Happy for this change to go into the original PR rather than this one, but I played around with this and [tests are now passing on my branch](https://github.com/scottgigante/anndata2ri/runs/7075242569?check_suite_focus=true)

**Comment by flying-sheep** [comment]
I created a PR from it: https://github.com/theislab/anndata2ri/pull/77

**Pull request closed without merging**
